---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.satyazzz123.online
  resources:
  - podlabelers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.satyazzz123.online
  resources:
  - podlabelers/finalizers
  verbs:
  - update
- apiGroups:
  - api.satyazzz123.online
  resources:
  - podlabelers/status
  verbs:
  - get
  - patch
  - update
